#ifndef FRONTEND_EXTENDED_H
#define	FRONTEND_EXTENDED_H

enum polarization
{
  POLARIZATION_HORIZONTAL,
  POLARIZATION_VERTICAL,
  POLARIZATION_CIRCULAR_LEFT,
  POLARIZATION_CIRCULAR_RIGHT
};

#endif	/* FRONTEND_EXTENDED_H */

