#pragma once
#include <Poco/Net/HTTPServerResponse.h>
#include <Poco/Net/HTTPServerRequest.h>
#include <Poco/Net/HTTPRequestHandler.h>
#include <Poco/Net/NetException.h>
#include <Poco/URI.h>
#include "Poco/Net/HTTPSClientSession.h"
#include "Poco/Net/HTTPClientSession.h"
#include "Poco/Net/NetException.h"
#include "Poco/Net/SSLException.h"
#include "Poco/Net/SSLManager.h"
#include "Poco/Net/KeyConsoleHandler.h"
#include "Poco/Net/PrivateKeyPassphraseHandler.h"
#include "Poco/Net/InvalidCertificateHandler.h"
#include "Poco/Net/AcceptCertificateHandler.h"
#include "Poco/Net/HTTPRequest.h"
#include "Poco/Net/HTTPResponse.h"
#include <Poco/Net/HTTPRequestHandlerFactory.h>
#include <boost/regex.hpp>
#include <boost/algorithm/string.hpp>
#include <boost/archive/iterators/base64_from_binary.hpp>
#include <boost/archive/iterators/insert_linebreaks.hpp>
#include <boost/archive/iterators/transform_width.hpp>
#include <yami4-cpp/parameters.h>
#include <yami4-cpp/incoming_message.h>
#include <yami4-cpp/parameters.h>
#include <exception>
#include "rapidjson/document.h"
#include "rapidjson/writer.h"
#include "rapidjson/stringbuffer.h"
#include "rapidjson/error/en.h"
#ifdef __linux__
#include <unistd.h>
#endif
#include <Poco/Net/HTTPServer.h>
#include <Poco/Net/HTTPServerParams.h>
#include <Poco/Net/ServerSocket.h>
#include <Poco/Net/NetworkInterface.h>
#include <yami4-cpp/yami.h>
#include <boost/program_options.hpp>
#include <signal.h>
#include <memory>
#include <set>
#include <iostream>
#include <map>
#include <fstream>
#include <vector>
#include <thread>
#include <string>
//#include <chrono>
#include <cstdlib>
#include "logger.h"
